services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: infoversedb
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  infoverse-api:
    container_name: infoverse-api-bsn
    image: infoverse-api:v2
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres
    restart: unless-stopped

  infoverse-api-ui:
    container_name: infoverse-api-ui-bsn
    image: infoverse-ui:v1
    ports:
      - 5000:5000
    networks:
      - spring-demo
    restart: unless-stopped

  jenkins:
    container_name: jenkins-bsn
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - C:\Users\user\.jdks\temurin-22:/jdk
    networks:
      - spring-demo
    restart: unless-stopped


networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  jenkins_data:
    driver: local