spring:
  servlet:
    multipart:
      max-file-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: ${EXP}

springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
  port: 8088

cors:
  set:
    allowed:
      origins: ${URL_FRONT}